sudo: required
services:
  - docker

before_install:
  - docker build -t cobyoyo/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true cobyoyo/docker-react npm run test -- --coverage

deploy:
  edge: true
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-2-869020886052"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id:
    secure: "Encrypted $AWS_ACCESS_KEY"
  secret_access_key:
    secure: "Encrypted $AWS_SECRET_KEY"
